# https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/crc/latest/crc-linux-amd64.tar.xz

name: CRC Tests on linux

on:
  workflow_dispatch:

jobs:
  smoke-tests:
    name: Run Smoke Tests Against OpenShift Local
    runs-on: ubuntu-24.04
    env:
      SHELL: /bin/bash
    steps:
      - name: Remove unwanted stuff
        uses: gbraad-actions/remove-unwanted@v1

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          args: --ssh --accept-dns=false
          hostname: crc

      - name: Change DNS settings
        run: |
          sudo systemctl disable --now systemd-resolved
          echo "nameserver 1.1.1.1" | sudo tee    /etc/resolv.conf
          echo "nameserver 4.4.4.4" | sudo tee -a /etc/resolv.conf

      - name: CRC
        uses: crc-org/crc-github-action@v1
        with:
          pull-secret: ${{ secrets.CRC_PULL_SECRET }}

      - name: use the podman env from crc preset
        run: |
          eval $(crc podman-env --root) && podman build -t quay.io/praveenkumar/myserver:v1 -f Containerfile .
      - name: Create resource (namespace/pod/service)
        run: |
          oc apply -f kubernetes/deploy.yaml
          oc wait --for=jsonpath='{.status.phase}'=Running pod/myserver -n demo
      - name: Create the route
        run: |
          oc expose service myserver -n demo
      - name: Get all the pods
        run: |          
          oc get pods -A
      - name: get the routes and access it with curl
        run: |
          oc get routes -n demo 
          curl -Ik myserver-demo.apps.crc.testing

      - name: Hang around
        run: sleep infinity